### ISSUE TITLE
merge button works, but I get a message: BUG: Invalid Path

### ISSUE THREAD

**Issue by timaschew** [philschatz/octokat.js#100]
Here is the message:

```
BUG: Invalid Path. If this is actually a valid path then please update the URL_VALIDATOR. path=/repos/MYORG/MYREPO/pulls/28/merge
```

**Comment by philschatz** [comment]
Thanks! f50b17b2cd808d7573e2cc6942cc88098c1dc279 should fix that. From #97 it seems you were working on committing multiple files using ES7; do you by chance have a code snippet you could share?
