### ISSUE TITLE
Not working in webpack

### ISSUE THREAD

**Issue by JakeCoxon** [philschatz/octokat.js#118]
I get this error when running with webpack

```
Error in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: 'child_process' in myapp/node_modules/xmlhttprequest/lib

 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
```

But I see there is a config to compile for the browser? Is the browser dist supposed to be on NPM?

**Comment by riongull** [comment]
I'm having the exact same issue as @JakeCoxon.  My project is using Webpack indirectly via [Gatsby](https://github.com/gatsbyjs/gatsby), specifically using the `gatsby develop` command.  Hot Module Replacement breaks.  Checking now to see if error still occurs when using other `gatsby` cli commands (which also call Webpack, but without HMR).
