### ISSUE TITLE
Repos releases not working?

### ISSUE THREAD

**Issue by Pauan** [philschatz/octokat.js#12]
I installed version 0.4.0 with npm, and I tried running this program in Node.js:

    var Octokat = require('octokat');

    var octo = new Octokat();

    octo.repos("philschatz", "octokat.js").releases.fetch().then(function (x) {
      console.log(x);
    });

This logs an empty array `[]`, even though the repo has multiple releases. Am I doing something wrong?

**Comment by Pauan** [comment]
Oh, I see, the Github API itself gives the same empty array. So the real issue is that octokat.js does not support getting the tags of a repository.

**Comment by philschatz** [comment]
Oops, that was an oversight on my part. If you do `npm update` you should be able to get the newest version and then use:

```js
var Octokat = require('octokat');
var octo = new Octokat();

octo.repos("philschatz", "octokat.js").tags.fetch().then(function (x) {
  console.log(x);
});
```

**Comment by Pauan** [comment]
Awesome, thanks! I'm impressed at the fast response.
