### ISSUE TITLE
Nesting of functions (eg. fromUrl)

### ISSUE THREAD

**Issue by petrpacas** [philschatz/octokat.js#153]
In my understanding the only way to get project's columns and their cards is to go about it like this:

```javascript
octo.fromUrl('/projects/xxxxxx/columns').fetchAll((e, cols) => {
  this.projectColumns = cols

  for (var col = 0; col < cols.length; col++) {
    var id = this.projectColumns[col].id

    octo.fromUrl('/projects/columns/' + id + '/cards').fetchAll((e2, cards) => {
      this.projectColumns[col].cardsList = cards
    })
  }
})
```

But for some reason the `col` variable doesn't get cycled through. The value of `col` in `this.projectColumns[col]` is always equal to `cols.length`.

It seems like I can't nest the `fromUrl` call inside the first one - like the second call gets executed outside the first call, after the first call ends.

Is this intended?

**Comment by philschatz** [comment]
This might be a scoping ""quirk" in JavaScript. You may need to add a closure around the inner `octo.fromUrl` (search for `do keyword` in http://coffeescript.org/ for an example).

Also, I believe you can write `.fromUrl('/projects/{projectId}/columns', {projectId: 123})` (or any [URL Template](https://en.wikipedia.org/wiki/URL_Template) ) if you did not want to perform the string concatenation yourself

**Comment by petrpacas** [comment]
The closure did help, thank you!
