### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by noeticpenguin** [philschatz/octokat.js#16]
First, let me thank you for your work here.

I was hoping you could provide an example of how to fork a repo?

I've tried:

```js
octo.repos('OriginalOwner', 'OriginalRepo').forks('noeticpenguin').create();
```

**Comment by philschatz** [comment]
if you are just forking to your account have you tried:

```javascript
octo.repos('OriginalOwner', 'OriginalRepo').forks.create();
```

If you want to fork to a particular Organization you can try:

```javascript
octo.repos('OriginalOwner', 'OriginalRepo').forks.create({organization: 'my-org'});
```

GitHub's documentation states that it may take a while to fork but if it does not work, can you include the error?

```javascript
octo.repos('OriginalOwner', 'OriginalRepo').forks.create({organization: 'my-org'}, function(err, val) {
  console.log(err);
  console.log(val);
});
```

**Comment by philschatz** [comment]
Marking this as closed; if it does not work, please re-open this issue.
