### ISSUE TITLE
Looks like comments update may have changes

### ISSUE THREAD

**Issue by ldh68579** [philschatz/octokat.js#191]
https://api.github.com/repos/jasongornall/always-green/issues/comments/312937694

`octo.repos('philschatz', 'octokat.js').issues(1).comments(123123).update({body: 'Hello'})` appears to crash for me

`
info: error Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"} PATCH https://api.github.com/repos/jasongornall/always-green/issues/1/comments/312939953 Status: 404
`

`octo.repos('philschatz', 'octokat.js').issues.comments(123123).update({body: 'Hello'})` works like a champ

```
info: Execution took 2627 ms, user function completed successfully
```

**Comment by philschatz** [comment]
Unfortunately, Octokat does not do a lot of runtime checking of URLs but it seems like you were able to get it working!

See #176 for static typechecking which would catch this error (if you use TypeScript). 

Closing this Issue for now but please reopen if this is still a problem.
