### ISSUE TITLE
How to create pull request

### ISSUE THREAD

**Issue by dhmlau** [philschatz/octokat.js#196]
How to create pull request the same way as the github REST API below? 
https://developer.github.com/v3/pulls/#create-a-pull-request

From the documentation, it seems like there's only pull request review.

**Comment by philschatz** [comment]
Are you able to run something like the following? (**Note:** you will need to be authenticated somehow)

```js
const octo = new Octokat({token: "..........."})

octo.repos('username', 'reponame').pulls.create({
  title: "My Pull Request title",
  head: "my-branch-name",
  base: "destination-branch-name",
  body: "Markdown describing the Pull Request",
  maintainer_can_modify: true
})
.then(function(val) { console.log(val) })
.catch(function(val) { console.error(val) })
```

**Comment by dhmlau** [comment]
Yes. I got that working.  Thanks a lot!
