### ISSUE TITLE
How do you create a new branch?

### ISSUE THREAD

**Issue by miztroh** [philschatz/octokat.js#21]
Can I get an example of creating a new branch?

**Comment by philschatz** [comment]
I think it would be (from <https://developer.github.com/v3/git/refs/#create-a-reference>):

```js
var sha = COMMIT_SHA_OF_OTHER_BRANCH;
repo.git.refs.create({ref: 'refs/heads/master', sha: sha}).then(...)
```

And you should be able to get the list of commits to a repository by <https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository>:

```js
repo.commits.fetch({sha: 'master'})
.then(function(commits) {

})
```

**Comment by miztroh** [comment]
Works for me.  Thanks!
