### ISSUE TITLE
Count number of issues/PRs?

### ISSUE THREAD

**Issue by zeke** [philschatz/octokat.js#31]
I'm considering using octokat on the npmjs.com website. We currently have some spaghetti-ish browserify code that hits the github API to display issue and pull request counts for npm packages:

![screen shot 2015-04-02 at 9 53 33 pm](https://cloud.githubusercontent.com/assets/2289/6978239/ff4cad00-d982-11e4-9670-4c4c407159bf.png)

We're using this One Weird Trick™ that @pengwynn taught us to fetch the counts: We set `per_page` to `1`, then use @thlorenz's [parse-link-header](https://github.com/thlorenz/parse-link-header) to pull the last page out of the response header. Because we only asked for one result, the last page is also the number of issues. This is a nice trick because it only requires a single request, even if there are hundreds of issues on the repo.

From the octokat README, I can see that the `per_page` option is supported, and attaches a `lastPage()` function to the response object, but that doesn't solve the problem of fetching the count. Is there a way to do this with octokat?

```js
new (require("octokat"))().repos("npm", "newww").issues.fetch({per_page: 1})
  .then(function() { console.log(arguments) })
```

cc @yashprit and @coleGillespie, who both have an interest in making this work on the npm website. :)

**Comment by philschatz** [comment]
Glad to hear you're considering `octokat`!

Currently you can get the URL via:

```js
new (require("octokat"))().repos("npm", "newww").issues.fetch({per_page: 1})
  .then(function(issues) { console.log(issues.lastPage.url) })
```

and then, (retrofitting `parse-link-header`):

```js
parselinkheader("<" + url + ">; rel=\"foo\"").foo.page
```

Assuming the URLs are relatively stable I'm pretty sure I can add these fields onto the `issues.lastPage` function like:

```js
new (require("octokat"))().repos("npm", "newww").issues.fetch({per_page: 1})
  .then(function(issues) { console.log(issues.lastPage.page) })
```

Getting this into `octokat` might be a little work but is that enough for you to be able to use this lib?

**Comment by zeke** [comment]
> is that enough for you to be able to use this lib

yes!

**Comment by zeke** [comment]
Using `url.parse()` to extract the `page` query param from `issues.lastPage.url` is working fine for me, but do let me know if you add the `lastPage.page` property. Thanks for the help!

**Comment by philschatz** [comment]
I have a branch at [#parse-querystring](https://github.com/philschatz/octokat.js/compare/parse-querystring) which extracts the fields out without requiring all of `url.js` but it seems like an uncommon-enough case that wouldn't warrant running this additional code on *every* link header.
