### ISSUE TITLE
Is code search broken ?

### ISSUE THREAD

**Issue by chicagogrooves** [philschatz/octokat.js#32]
In NodeJS,
Works:
` github.search.issues.fetch({q: "term", repo: "someone/somewhere"}).then(log)`
Doesn't
` github.search.code.fetch({q: "term", repo: "someone/somewhere"}).then(log)`

I see the test is commented out for code
https://github.com/philschatz/octokat.js/blob/master/test/simple.spec.coffee#L148

**Comment by philschatz** [comment]
It looks like the recommended way to search for both issues and code is to include the repo in the `q` field. <https://help.github.com/articles/searching-issues/#search-within-a-users-or-organizations-repositories>

- [search issues](https://developer.github.com/v3/search/#search-issues)
- [search code](https://developer.github.com/v3/search/#search-code)

The following should work:
```js
github.search.code.fetch({q: "grammar repo:philschatz/octokat.js"}).then(log)
```

**Comment by chicagogrooves** [comment]
Yup, you're right.
