### ISSUE TITLE
\u0000 appended in string returned from readBinary

### ISSUE THREAD

**Issue by matthewbauer** [philschatz/octokat.js#37]
I'm not sure if this is on GitHub's end or octokat but there is a null terminator code being appended to my content return from .readBinary(). Right now, I can just get rid of it, but I'm thinking it's an issue.

**Comment by philschatz** [comment]
If you want to try to debug the relevant code is in [src/request.coffee#L192](https://github.com/philschatz/octokat.js/blob/master/src/request.coffee#L192) but I do not see anything involving a null character.

I can try to investigate but it may take some time before I start.

**Comment by matthewbauer** [comment]
Sure. It's possible that GitHub just appends \0 to everything that's base64 encoded. There's an easy workaround so it's no big deal. I just wanted to report where I was having issues.

**Comment by matthewbauer** [comment]
Okay, I just caught it. Line 197 should use CoffeeScript's ... instead of ..

https://github.com/philschatz/octokat.js/blob/master/src/request.coffee#L197

**Comment by philschatz** [comment]
Thanks for finding this. Want to make a Pull Request?
