### ISSUE TITLE
Run replacer on already fetched JSON data

### ISSUE THREAD

**Issue by matthewbauer** [philschatz/octokat.js#39]
I'm working with handling GitHub's webhooks and each payload contains JSON resource info on the resource changed by the event. It would be nice to be able to run the replacer on it without actually sending a request. Basically, I want to be able to fetch some other resources without having to construct them myself. I think this might be possible without changing anything, so any suggestions would be helpful.

**Comment by philschatz** [comment]
Hmm, I'm not sure what you mean by this. Are you fetching JSON from another site (other than `api.github.com`) that uses the same JSON naming conventions? The tricky bits would be handling `*_url` fields; especially the authentication keys if the JSON is not public.

If so, the replacer could maybe be exposed as something like `octo.JSONReplacer(obj)`.

But if you don't need to convert `*_url` fields then there may be a smaller package that just recursively converts `_`-fields to `camelCase`.
