### ISSUE TITLE
review_comments_url and review_comments overwrite each other

### ISSUE THREAD

**Issue by matthewbauer** [philschatz/octokat.js#41]
I'm not sure the best way to handle this, but pull requests have fields for both review_comments and review_comments_url. Since review_comments_url comes first, it is overwritten by review_comments. What is the best way to handle it? The same is true for comments.

The best fix I can think of is prefixing one of them with an _.

You can look at the diff here of a possible solution here: https://github.com/matthewbauer/octokat.js/commit/c8719ab0afe1423a5e3033175a5871da5c2c538a

**Comment by philschatz** [comment]
hmm, I'll need to check other places where the JSON keys overlap but maybe suffixing with `Count` for the non-URL ones?

**Comment by philschatz** [comment]
Thanks for the feedback! Sorry it took so long to respond. #81 splits octokat into smaller pieces so users can opt-in to different features (like `camelCase`, Hypermedia, sending binary files) to address this and other issues people have found. 

I hope that helps address this annoying "feature" :smile: . Any thoughts/feedback on #81 are definitely appreciated!

**Comment by matthewbauer** [comment]
Ok looks good to me!
