### ISSUE TITLE
Unimplemented API: can't add label to issue

### ISSUE THREAD

**Issue by vslinko** [philschatz/octokat.js#52]
https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

`repo.issues(number)` has no `labels` key

**Comment by vslinko** [comment]
It means I can't use https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue also

**Comment by philschatz** [comment]
This should be addressed in `0.4.11` as part of #47 (just released a new version).

If not, please reopen this issue.

**Comment by chrisjshull** [comment]
can you give an example of how to do this?

**Comment by philschatz** [comment]
To update the set of Issues on a label you should be able to do:

```
# Option 1
promise = octo.repos(repoOwner, repoName).issues(issue.number).update({labels: labelNames})

# Option 2 (from https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue. should also work)
p = octo.repos('philschatz', 'octokat.js').issues(1).labels.create(['bug'])
```

[gh-board example](https://github.com/philschatz/gh-board/blob/master/src/issue-store.js#L415)


and to create a new label:
```
promise = octo.repos(repoOwner, repoName).labels.create({name: 'bug2', color: '000000'})
```

[gh-board example](https://github.com/philschatz/gh-board/blob/master/src/issue-store.js#L447-L449)

Hope that helps!
