### ISSUE TITLE
Small (but annyoing) error in bower.json

### ISSUE THREAD

**Issue by jschrewe** [philschatz/octokat.js#54]
The line 

```js
"main": "octokat.js",
```

in `bower.json` shoiuld read

```js
"main": "dist/octokat.js",
```

otherwise tools like [main-bower-files](https://github.com/ck86/main-bower-files) can't be used to automatically bundle octokat.

I tend to feel a tad stupid for making pull request for such tiny things, but if you want I can make on.

**Comment by philschatz** [comment]
Thanks for catching that! I pushed the change to master and it will be included in the next minor version release
