### ISSUE TITLE
Octocat and ember extending prototype

### ISSUE THREAD

**Issue by mokkabonna** [philschatz/octokat.js#55]
I have use the latest ember cli (1.13.6) to generate a default project.

Seems ember are extending array prototype. (which probably is a bad idea on their part anyway)

In my ember route I do the following:

` return octo.users('mokkabonna').repos.fetch({per_page:1})`

The code trips out here with maximum callstack error:
https://github.com/philschatz/octokat.js/blob/master/src/replacer.coffee#L59

In particular it seems when octokat encounters a key named " super" (notice the leading space)

Sure it shouldn't be if typeof value instead of key? Isn't key always a string? If i change it to that it seems fine.

Anyway isn't it better to use `Object.keys`? Or if you want to support es3, use at least use this:

```javascript
for (var name in buz) {
  if (buz.hasOwnProperty(name)) {
    console.log('this is fog (' + name + ') for sure. Value: ' + buz[name]);
  }
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

**Comment by philschatz** [comment]
I submitted #57 which should fix the issue you mentioned. Do you mind verifying that it works?

**Comment by mokkabonna** [comment]
Using https://raw.githubusercontent.com/philschatz/octokat.js/use-object-keys/dist/octokat.js instead it worked as expected.

**Comment by mokkabonna** [comment]
Closing this issue in favor of #57
