### ISSUE TITLE
BUG: Invalid Path when accessing git.refs('tags/tagname')

### ISSUE THREAD

**Issue by mokkabonna** [philschatz/octokat.js#56]
I get 
> BUG: Invalid Path. If this is actually a valid path then please update the URL_VALIDATOR. path=/repos/owner/reponame/git/refs/tags/mytag

When calling

```js
octo.repos('owner', 'reponame').git.refs('tags/mytag')
```

Ideally I guess you should have been able to do:

```js
octo.repos('owner', 'reponame').git.refs.tags('mytag')
```

Like if it was a branch:

```js
octo.repos('owner', 'reponame').git.refs.heads('mybranch')
```

But tags is not a property of refs, so that fails.

Is it only to add **tags** here? https://github.com/philschatz/octokat.js/blob/master/src/grammar.coffee#L157 Or should maybe refs allow for any custom path after? Isn't that ok in git (and github). Like github itself uses with refs/pr/# (or something)

Then we could do 

```js
octo.repos('owner', 'reponame').git.refs('myrefcategory/mysomething')
```

Anyway for a built in feature like tags I think it should be possible to it directly like shown before with `regs.tags(tagname)`

**Comment by philschatz** [comment]
Yep, I think you could add `/tags` to the line you referenced (plus add an entry to [grammar.coffee#L342](https://github.com/philschatz/octokat.js/blob/master/src/grammar.coffee#L342) ). If those are added you could probably also just call `octo.repos('owner', 'reponame').git.refs('tags/mytag')`.

Would you mind submitting a Pull Request with those changes?
