### ISSUE TITLE
Adding organisations endpoint

### ISSUE THREAD

**Issue by bitoiu** [philschatz/octokat.js#66]
Hi @philschatz,

I was trying to use your lib for listing all organisations: https://developer.github.com/v3/orgs/#list-all-organizations but I'm having a hard time figuring out what I'm missing.

Instead of just calling the API directly I want to learn how to improve this library, so I went to grammar and added `organisations` as a top level path.

I didn't apply any changes to the OBJECT_MATCHER: https://github.com/philschatz/octokat.js/blob/master/src/grammar.coffee#L414

When I know how to add this one, I plan on adding a few others like adding users etc, i.e. the `admin` path.

*Note: I'm going to try and debug your code and use a proxy to know what's coming out of my terminal and I hope to get there in the meantime.*

**Comment by philschatz** [comment]
To add support for `/organizations` all you should need to do is:

1. add an entry to `TREE_OPTIONS` (ie `'organizations': false` just after line 234)
2. optionally add an entry to the `URL_VALIDATOR` (ie `| organizations` just after line 17)

The first step allows the following code to *just work*:

```js
var octo = require('octokat')();
// if you are running this in the octokat.js dir you can use `octo = require('./')();` instead

octo.organizations.fetch()
.then(function (orgs) {
  console.log(orgs.length);
  // The next lines grab the 2nd page of orgs
  orgs.nextPage().then(function (moreOrgs) {
    console.log(moreOrgs.length);
  });
});
```

The second step removes the warning that the URL may be invalid.

Also, be sure to run `grunt dist` to rebuild the files (if you're using it in node or in the browser).

Hope that helps!

**Comment by bitoiu** [comment]
hey @philschatz thanks for this!

I will test this tonight if possible, I though I've done both steps you've described but without success. I'll try again tonight and if successful I'll send a PR.

:bow::sparkles:

**Comment by bitoiu** [comment]
Hey @philschatz, I'm having troubles testing this endpoint. That would explain why this didn't work for me yesterday and I did very similar changes.

I have the code ready to send the PR, just need to test it for a bit and make sure everything is ok.

Thanks for your help.
