### ISSUE TITLE
Adding a member

### ISSUE THREAD

**Issue by bitoiu** [philschatz/octokat.js#69]
Hey @philschatz, sorry to bug you again.

I'm trying to run `PUT /teams/:id/members/:username` on a GHE instance, by using:

```javascript
octo.teams('153').members.add('aaa',cb) // or
octo.teams('153').members.add('aaa')
```

Team `153` exists and I can fetch it. I can also run the following in POSTMAN and it works if I do:

`PUT https://GHEINSTANCE/api/v3/teams/153/members/aaa`
`DELETE https://GHEINSTANCE/api/v3/teams/153/members/aaa`

I've checked the source and `add` maps to PUT so I'm not sure what I'm missing.

PS: All the help you give I will put back in help other octokat.js users and by providing as many PRs as I can.

**Comment by philschatz** [comment]
Hmm, odd. Other `PUT` requests like starring repos works for me, could you confirm on a GHE instance? I'll try replicating adding team members later today (I don't have access to a GHE instance but I'll try it on GH).

**Comment by philschatz** [comment]
Hmm, I was able to add a user to a team by doing the following:

```js
var octo = new Octo({token: TOKEN_WITH_WRITE_ACCESS});
octo.teams(123).members('aaa').add(cb);
```

Initially, the user I was testing with was not part of the organization (I got a 422) so I had to add them, but then it worked. What error did you get?

**Comment by bitoiu** [comment]
@philschatz now that I see your syntax, I was wrong:

> octo.teams('153').members.add('aaa')

vs

> octo.teams('153').members('aaa').add()

Sorry for this, my bad.

**Comment by philschatz** [comment]
aha! the argument to `.add` is different! the arguments to `.add`, `.fetch`, and other verb methods do not become part of the URL, they become query parameters.

I should clarify that in the `README` :smile:

**Comment by bitoiu** [comment]
I mention octokat on the scripts I wrote: https://github.com/bitoiu/github-enterprise-scripts

There's two or 3 methods I'm still using native requestjs, but I'll change those soon.
