### ISSUE TITLE
Release uploads don't work anymore

### ISSUE THREAD

**Issue by mokkabonna** [philschatz/octokat.js#72]
I use octokat.js with github enterprise. 

Recently we updated from 2.3 to 2.4 and now I can't upload release assets anymore. The error I get is: 
```js
{"message":"Invalid name for request","request_id":"b419e46f-86bd-11e5-8e9a-c8998822e9ce"}
```

I have pinpointed the error to an change in the upload_url reported by github api:

in 2.3 it was https://developer.github.com/enterprise/2.3/v3/repos/releases/#get-a-single-release
```
  "upload_url": "https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name}",
```

in 2.4 it is https://developer.github.com/v3/repos/releases/#get-a-single-release
```
 "upload_url": "https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}",
 ```

This causes the templating in octokat to produce this url: 
https://github.oslo.kommune.no/api/uploads/repos/pet/minside/releases/444/assets?name,label=deploy.tar.gz

when before it would have been: 
https://github.oslo.kommune.no/api/uploads/repos/pet/minside/releases/444/assets?name=deploy.tar.gz

The code I have, before and now:

```js
release.upload('deploy.tar.gz', 'application/x-gzip', grunt.file.read('dist/deploy.tar.gz', {
  encoding: null //return buffer
}));
```

Is there anyway I can change this to make it work still, or is this just a bug that need to be fixed? I have tried with no success: 

```js
release.upload('deploy.tar.gz', 'somelabel', 'application/x-gzip', grunt.file.read('dist/deploy.tar.gz', {
  encoding: null //return buffer
}));
```

Also:
```js
release.upload({
  name: 'deploy.tar.gz',
  label: 'somelabel',
}, 'application/x-gzip', grunt.file.read('dist/deploy.tar.gz', {
  encoding: null //return buffer
}));
```

Does octokat.js not support multiple query params? Or is it filling it out last to first?

**Comment by mokkabonna** [comment]
It seems they had the same issue in the .net octokit: https://github.com/octokit/octokit.net/issues/894

**Comment by philschatz** [comment]
Thanks! I don't use the resource upload feature so I don't have any tests for it yet. `octokat` does not yet support multiple optional parameters from a URL template but I think the `upload_url` is the only pattern so far that I've seen that contains multiple optional params.

I have a Pull Request (linked to this issue) which should solve the immediate problem, but it only supports setting the name field (no label yet).

**Comment by mokkabonna** [comment]
It works well. It would be great if this could be released as a fix. Not being able to set the label is not that bad and can be added later. Anyway you can edit the label post upload: https://developer.github.com/v3/repos/releases/#edit-a-release-asset

**Comment by mokkabonna** [comment]
Notifications seem to have multple query params as well: 

 "notifications_url": "http://api.github.com/repos/octocat/Hello-World/notifications{?since, all, participating}",

**Comment by philschatz** [comment]
I merged the Pull Request and can create a new release but before I do can you verify it still works? I added the option of doing `release.upload('deploy.tar.gz', 'application/x-gzip', ...)` or `release.upload({name: 'deploy.tar.gz', label: 'somelabel'}, 'application/x-gzip', ...)`

**Comment by mokkabonna** [comment]
It still works as expected.

I tried both with string only and with object. Both functions as expected.

**Comment by philschatz** [comment]
Thanks! `octokat@0.4.13` is up on npm

**Comment by mokkabonna** [comment]
:+1:
