### ISSUE TITLE
Auth required when using in the browser?

### ISSUE THREAD

**Issue by zeke** [philschatz/octokat.js#74]
I'm logged into github.com in my browser. When I make an in-browser request using octokat, does my cookie get used, or do I have to explicitly supply an OAuth token?

**Comment by philschatz** [comment]
You have to provide an OAuth token or use the free 60 requests/hr (rate limited by IP); otherwise a random website could have a lot of fun with your account :smile:

**Comment by zeke** [comment]
Got it. Thanks!
