### ISSUE TITLE
is there a way, give an issue.url, to update it?

### ISSUE THREAD

**Issue by sam-github** [philschatz/octokat.js#76]
I have an issue fetched from github, I have it's `issue.url` (for example, `https://api.github.com/repos/some-org/a-repo/issues/990`), and now I want to update it.

ATM, it looks like I need to do a `url.parse()`, then split the path, find `some-org` and `a-repo` by direct indexing into the path, and then I can call `octo.repos('some-org', 'a-repo').issues(issue.number).update({labels: labels}, ...`.

I suspect that there is a better way, since I've already got the URL partially constructed, can you point me to it?

**Comment by philschatz** [comment]
Unfotunately the only URL parsing octokat does besides validation is to determine the type of the object returned in the JSON.

See https://github.com/philschatz/octokat.js/blob/master/src/grammar.coffee#L407-L411

But it might make sense to offer _root_ verb methods whose 1st argument is a URL. Something like:

```js
octo = new Octokat();
octo.verbs.fetch(url, cb)
octo.verbs.update(url, {title: 'new title'}, cb)
octo.verbs.fetch(url).then(...)
```

**Comment by philschatz** [comment]
Howdy! I added #78. Hope that helps!
