### ISSUE TITLE
Basic how-to for in-browser?

### ISSUE THREAD

**Issue by dogweather** [philschatz/octokat.js#83]
Hi, I'm new to Javascript, and am trying to get a simple query running in the browser.

It looks like RequireJS is necessary because dist/octokat.js has the `require` statement. So I've installed octokat via bower, and downloaded requirejs. RequireJS is new to me, though, and has a ton of complexity. I'm trying to configure it, e.g.:

```html
  <script data-main="bower_components/octokat/dist/octokat" src="require.js"></script>
```

 and it's failing with:

```
Uncaught Error: Module name "plus" has not been loaded yet for context: _. Use require([])
```

So I see that there's plus.coffee in the src/ directory... what else should I do to simply get this working?

Thanks!

**Comment by philschatz** [comment]
Hmm, I don't think you need `requirejs` to use `octokat`. Here's what I did to get it working quickly using bower. Hopefully these steps will help:

```sh
mkdir octokat-test
cd oktokat-test
bower install octokat
```

Create an HTML file like the following:

```html
<html>
  <body>
    <script src="./bower_components/octokat/dist/octokat.js"></script>
    <script>
      var octo = new Octokat();
      octo.repos('philschatz', 'octokat.js').fetch(function(err, repo) {
        if (err) { return alert(err); }
        alert(repo.url); 
      });
    </script>
  </body>
</html>
```

and then open it up in a browser. I used [http-server](https://www.npmjs.com/package/http-server)

## Screenshot

![image](https://cloud.githubusercontent.com/assets/253202/11950106/6349dae0-a853-11e5-8206-dcb3cbf95c2b.png)

I hope that helps!

**Comment by dogweather** [comment]
Fantastic, thanks! I followed these steps and it works fine. 

For some reason in my original project, I get `Uncaught ReferenceError: require is not defined`. But I started that project with a yeoman template, and I only barely know how that all works, so I'm sure there's some configuration affecting things.

**Comment by dogweather** [comment]
As crazy as this sounds, I think it had something to do with my ruby installation.
