### ISSUE TITLE
Example of OAuth in the browser?

### ISSUE THREAD

**Issue by dogweather** [philschatz/octokat.js#85]
I'm wondering what steps are required to use the OAuth support. I'm guessing that first one must register the app with GitHub. But in that process I didn't see an "oauth_token" presented. Is something like [hello.js](https://adodson.com/hello.js/) necessary?

I'm making an app to analyze repo management styles. Currently, it supports just unauthenticated mode and password authentication. http://repocheck.com

**Comment by philschatz** [comment]
I don't think you can do OAuth directly in the browser. Also, I'm not sure how secure `hello.js` is because it seems the browser will get keys that can then be used on other sites and the only way to revoke them is to revoke the `hello.js` key for your application (which would affect all users). For [gh-board](https://github.com/philschatz/gh-board) I use tokens which the user creates (and can revoke).

There are instructions if you go to http://philschatz.com/gh-board and click <kbd>Sign In</kbd>.

Hope that helps!

**Comment by philschatz** [comment]
If you find that `hello.js` is actually secure, please let me know!

Also, I just checked out your project... Nice use of the Paged Results API! Did you know you can send `...fetch({per_page: 100})`?

**Comment by dogweather** [comment]
Thanks. Yep, I'm using your `fetchAll` function you posted in another comment:

```coffeescript
  fetchIssues: (repo) =>
    # https://developer.github.com/v3/issues/#list-issues-for-a-repository
    # https://developer.github.com/guides/traversing-with-pagination/#basics-of-pagination
    options = {per_page: 100, state: 'all', since: App.Github.oneMonthAgo()}
    App.octoFetchAll(repo.issues.fetch, options).then (
      (issues) =>
        @rawdata.issues = issues
        @issuesCallback(this)
      )
      .catch(@errorCallback)
```

**Comment by dogweather** [comment]
And I display progress with an extra line in fetch all. Not the most elegant, but it works for now:

https://github.com/dogweather/repo-health-check/blob/master/src/octokat-ext.js#L6

**Comment by philschatz** [comment]
Hmm, maybe the combination of `plugins/fetch-all` and `plugins/emitter` #81 would get you enough information to not have to include the 1-line addition to octokat? and creating a new plugin for the URL parsing in the response JSON?

**Comment by keshavsaharia** [comment]
I think the original question was about implementing OAuth with GitHub and retrieving a user access token. I don't recommend the gh-board approach of having users generate their own token.

I just uploaded a simple Express script to this repository for doing this: https://github.com/keshavsaharia/github-oauth
