### ISSUE TITLE
SearchIssues Function Replacement?

### ISSUE THREAD

**Issue by lmstearn** [philschatz/octokat.js#86]
Running a [script](http://gitlab.theassimilationlab.com/deaths_soul/boss/raw/master/resources/script.js) that works well with a previous iteration of Octokit,

The relevant line starts with: 

`searchIssues(pluginName + ' in:title repo:' + repos[gameName].owner + '/' + repos[gameName].repo).then(function(issues)`

Is there a replacement function in Octokat for this, or does the current code need refactoring to suit?

Thanks :)

**Comment by philschatz** [comment]
To search Issues, you should be able to do something like the following:

```
var o = new Octokat({token: ...});
var query = pluginName + ' in:title repo:' + repos[gameName].owner + '/' + repos[gameName].repo;
o.search.issues.fetch({q: query}).then(function(issues) { ... });
```

Hope that helps!

**Comment by philschatz** [comment]
If this did not help, please feel free to reopen this issue.

**Comment by lmstearn** [comment]
Thanks, we haven't gotten round to testing yet, but will yell come the unforeseen!

**Comment by lmstearn** [comment]
@philschatz: Still have a problem with a replacement for the old issues object from Octokit..
Trying "var issue = new Issue(repos[gameName].owner, repos[gameName].repo, issues.items[i].number);" and other lines using that object and its functions(issue.getComments().then(function(comments) { and issue.createComment(comment).then(function(data) {) need to be updated as well.
