### ISSUE TITLE
Patch?

### ISSUE THREAD

**Issue by RichardLitt** [philschatz/octokat.js#89]
How do I use a PATCH method? 

Example: octo.repos(result.owner.login, result.name).update({
          description: 'test'
        })

Thanks.

**Comment by philschatz** [comment]
It depends on if you are using callbacks or promises.

With promises:

```
octo.repos(result.owner.login, result.name).update({description: 'test'})
.then(function(updatedObject) {
  console.log(updatedObject);
});
```

With callbacks:

```
function cb(err, updatedObject) {
  console.log(updatedObj);
};
octo.repos(result.owner.login, result.name).update({description: 'test'}, cb);
```

**Comment by RichardLitt** [comment]
Hmm. I've tried that.

Repo: https://github.com/RichardLitt/gh-description

```sh
node cli.js RichardLitt/awesome-nomad test
```
It's still not working. :/ Thoughts?

**Comment by philschatz** [comment]
Ah, according to https://developer.github.com/v3/repos/#edit it seems GitHub requires the `name` to be provided as well. Without the `name` I got a 422 response but once I added the `name` the description updated.

**Comment by RichardLitt** [comment]
So, I tried that, and it still is returning this: 

```js
{ [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  status: 404,
  json: 
   { message: 'Not Found',
     documentation_url: 'https://developer.github.com/v3' } }
```

I'm still not sure if this is my fault.

**Comment by RichardLitt** [comment]
The only difference between a working call and a failing one is turning `.fetch()` into `.update({'name': 'test-repo', 'description: 'test'})`. Doesn't look like it is a problem on my end.

**Comment by philschatz** [comment]
It seems the OAuth scope for the key that is generated is "public access" which is not enough to edit repo details. It would need to have either `public_repo` or `repo`. See https://developer.github.com/v3/oauth/#scopes for more details.

**Comment by RichardLitt** [comment]
Fixed by deleting the config file and then adding scopes. Didn't work previously due to not overwriting the ghauth config file. Thanks!

**Comment by RichardLitt** [comment]
I have the same Not Found bug again, and I have no idea how to diagnose it. How can I find out what URL is being used to hit the GitHub server?

**Comment by RichardLitt** [comment]
> Fixed by deleting the config file and then adding scopes. Didn't work previously due to not overwriting the ghauth config file. Thanks!

Did the same thing. Not sure why I keep running up against this. Not this module's bug at all. 

<3 thank you for helping. Sorry for being a bit obstinate.
