### ISSUE TITLE
npm package contains a large zip file with dev dependencies

### ISSUE THREAD

**Issue by ummels** [philschatz/octokat.js#93]
When I do `npm install octokat` the resulting node module contains a 26 MB large ZIP file with all dev dependencies called `node_modules.zip`, which does not seem necessary for using octokat as a library. This is problematic because when I want to include octokat in my own node module for use on AWS Lambda, I need to package it with all dependencies and the resulting package file becomes hard to upload when it is larger than 10 MB.

**Comment by philschatz** [comment]
Thanks for pointing out that oversight! `0.4.17` should no longer have that zip file included.

**Comment by ummels** [comment]
Great. Thanks.
