### ISSUE TITLE
File read doesn't work in strict mode

### ISSUE THREAD

**Issue by koluch** [philschatz/octokat.js#99]
Hi,

I tried to run this example from README in my browser:

``` js
var octo = new Octokat();
var repo = octo.repos('philschatz', 'octokat.js');
repo.contents('README.md').read() // Use `.read` to get the raw file.
.then(function(contents) {        // `.fetch` is used for getting JSON
  console.log(contents);
});
```

... but it fails with following error:

```
verb-methods.js:76 Uncaught TypeError: Cannot create property 'url' on string '# Octokat.js
```

Error line is following (verb-methods.js:76):

``` js
      obj.url = path;
```

Somehow, `obj` becomes a response string, and it's forbidden to make new properties for strings in strict mode.

**Comment by timaschew** [comment]
It works fine for me on this demo page: https://tonicdev.com/npm/octokat

**Comment by philschatz** [comment]
Closing this because the code seems to work on tonicdev (Thanks @timaschew for responding!) 

If it does not work, please reopen the Issue
